name: Version Deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH keys
        run: | 
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{secrets.SSH_HOST}} >> ~/.ssh/known_hosts

      - name: Copying Files
        run: |
          rsync -avz --exclude = '.git' --exclude = '.github' ./ ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:/var/www/html/
          

